### PR TITLE
Update to Rust 1.4 and recent Piston libs

### PR DESCRIPTION
**Pull request by jorendorff**
The first patch here simply updates the program so it'll build with the latest versions of Rust and Piston.

The second patch fixes a bug, and the last one fixes travis-ci support. The third patch is just for fun.

### CODE REVIEW

**Comment by jorendorff** [comment]
Now passing all 0 tests on travis! \o/ :tada:

**Comment by Arcterus** [comment]
Oh sorry I totally forgot about this :/

I'll probably try to finagle your bug fix (although I can't replicate the issue?) and the drawing in (cause that seems fun).

**Comment by Arcterus** [comment]
Also, yes, I should probably be testing more of the code but this was pretty much just a "for fun" thing.

**Comment by jorendorff** [comment]
Heh! I didn't mean to ding you for not having tests, just goofing around. :)

**Comment by Arcterus** [comment]
I didn't really think you meant anything bad by it lol

**Comment by Arcterus** [comment]
If you have time at some point can you let me know if the bug is still an issue, because I am having problems reproducing it.

**Comment by jorendorff** [comment]
I cloned your repo fresh, did `cargo run`, moved the mouse pointer over the window, clicked and dragged the mouse pointer outside the window.

As soon as the mouse pointer left the window, the program died with:

```
press mouse button: Left
thread 'main' panicked at 'assertion failed: x <= WINDOW_WIDTH / BLOCK_SIZE', src/life.rs:202
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Arcterus** [comment]
Huh, weird.  Are you on Linux or macOS?  The behavior must be different on Windows...

**Comment by jorendorff** [comment]
> Huh, weird. Are you on Linux or macOS?

Mac. I think I was running Linux when I originally submitted the patch, though.

> The behavior must be different on Windows...

Oh, that seems likely—maybe the library doesn't deliver mouse events outside the window on Windows.

**Comment by Arcterus** [comment]
I'll try to update your patch and test it on Linux then :)

**Pull request closed without merging**
